version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: anime-postgres
    restart: always
    environment:
      POSTGRES_USER: anime_user
      POSTGRES_PASSWORD: anime_pass
      POSTGRES_DB: anime_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: